// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';
import {app} from '../models';

export function Config():Promise<config.Config>;

export function Ctx():Promise<context.Context>;

export function Log():Promise<app.Log>;

export function SetCtx(arg1:context.Context):Promise<void>;
